
version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "89:8080"
    environment:
      - SWAGGER_JSON=/swagApp/swagger.json
    volumes:
      - /home/zain/word-count-bee:/swagApp

  golang-application:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - "8080:8080"
    depends_on:
      - postgres-database

  postgres-database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
