
version: '3'

services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db_1_1

  postgres-db_1_1:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
